CREATE DATABASE ADM_CLUB;

USE ADM_CLUB;

CREATE TABLE USUARIO

(
	CPF				VARCHAR(11)			NOT NULL,
	NOME			VARCHAR(20)			NOT NULL,
	SOBRENOME		VARCHAR(50)			NOT NULL,
	N_DEPENDENTES	INT					NOT NULL,
	DATA_ASSOCIACAO	DATETIME			NOT NULL
	CONSTRAINT PK_USUARIO PRIMARY KEY (CPF)
);

CREATE TABLE TIPO_ENDERECO

(
	ID				INT				NOT NULL IDENTITY(1,1),
	NOME			VARCHAR(50)		NOT NULL,
	DESCRICAO		VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_ENDERECO PRIMARY KEY(ID)
);

CREATE TABLE UF

(
	ID		INT			NOT NULL IDENTITY(1,1),
	NOME	VARCHAR(2)	NOT NULL,
	CONSTRAINT PK_UF PRIMARY KEY (ID)
);

CREATE TABLE CIDADE

(
	ID		INT			NOT NULL IDENTITY(1,1),
	ID_UF	INT			NOT NULL,
	NOME	VARCHAR(50)	NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID),
	CONSTRAINT FK_CIDADE_UF FOREIGN KEY(ID_UF)
	REFERENCES UF(ID)
);

CREATE TABLE ENDERECO

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_TIPO_ENDERECO	INT				NOT NULL,
	ID_USUARIO			VARCHAR(11)		NOT NULL,
	ID_CIDADE			INT				NOT NULL,
	LOGRADOURO			VARCHAR(100)	NOT NULL,
	BAIRRO				VARCHAR(50)		NOT NULL,
	NUMERO				VARCHAR(20)		NOT NULL,
	CEP					VARCHAR(20)		NOT NULL,
	CONSTRAINT PK_ENDERECO PRIMARY KEY (ID),
	CONSTRAINT FK_ENDERECO_TIPO_ENDERECO FOREIGN KEY (ID_TIPO_ENDERECO)
	REFERENCES TIPO_ENDERECO(ID),
	CONSTRAINT FK_ENDERECO_USUARIO FOREIGN KEY(ID_USUARIO)
	REFERENCES USUARIO(CPF),
	CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY(ID_CIDADE)
	REFERENCES CIDADE(ID)
);

CREATE TABLE ANO_MENSALIDADE

(
	ID				INT				NOT NULL IDENTITY(1,1),
	ANO				VARCHAR(4)		NOT NULL,
	CONSTRAINT	PK_ANO_MENSALIDADE PRIMARY KEY(ID)
);

CREATE TABLE MES_MENSALIDADE

(
	ID		INT			NOT NULL IDENTITY(1,1),
	ID_ANO	INT			NOT NULL,
	MES		VARCHAR(20)	NOT NULL,
	CONSTRAINT PK_MES_MENSALIDADE PRIMARY KEY(ID),
	CONSTRAINT FK_MES_MENSALIDADE_ANO_MENSALIDADE FOREIGN KEY(ID_ANO)
	REFERENCES ANO_MENSALIDADE(ID)
);

CREATE TABLE MENSALIDADE

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_USUARIO			VARCHAR(11)		NOT NULL,
	VALOR				DECIMAL(10,2)	NOT NULL,
	DATA_VENCIMENTO		DATETIME		NOT NULL,
	DATA_PAGAMENTO		DATETIME		NOT NULL,
	CONSTRAINT PK_MENSALIDADE PRIMARY KEY(ID),
	CONSTRAINT FK_MENSALIDADE_USUARIO FOREIGN KEY(ID_USUARIO)
	REFERENCES USUARIO(CPF),
	CONSTRAINT FK_MENSALIDADE_MES FOREIGN KEY(ID)
	REFERENCES MES_MENSALIDADE(ID)
);
